name: Notify discord

on:
    workflow_dispatch:
    push:
        branches: [ main ]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            -   name: Request webhook
                uses: tsickert/discord-webhook@v5.3.0
                with:
                    webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                    content: "${{ github.event.repository.full_name }}'s main branch got a push at ${{ github.event.repository.updated_at }} by ${{ github.actor }}."
                    username: "davidsaltacc.github.io status"