name: Notify discord

on:
    workflow_dispatch:
    push:
        branches: [ main ]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            -   name: Send request to webhook
                uses: tsickert/discord-webhook@v5.3.0
                with:
                    webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                    content: "${{ github.event.repository.full_name }}'s main branch got a push at ${{ github.event.repository.updated_at }} by ${{ github.actor }}. Youngest commit message: ${{ github.event.head_commit.message }}"
                    username: "davidsaltacc.github.io status"
            -   name: Log event
                env:
                    EVENT_CONTEXT: ${{ toJson(github.event) }}
                run: |
                    echo "$EVENT_CONTEXT"
